### ISSUE TITLE
Installing required software

### ISSUE THREAD

**Issue by pakiessling** [RCHENLAB/SpatialMmMERFISH#6]
Thank you for the very cool paper.

I am interested in trying out some of your analysis methods.

Would it be possible to share a docker/requirements.txt/conda_enviroment.yml?

**Comment by jongsuc** [comment]
Hi,

I used two separate conda environments for cell segmentation and downstream analysis. 
The below are .yml files converted to .txt for attachment purposes.
Let me know if you have more questions. 

Thanks!

[cell_segmentation.txt](https://github.com/RCHENLAB/SpatialMmMERFISH/files/10493350/cell_segmentation.txt)
[downstream_analysis.txt](https://github.com/RCHENLAB/SpatialMmMERFISH/files/10493351/downstream_analysis.txt)

**Comment by pakiessling** [comment]
@jongsuc Perfect, thank you so much
